### PR TITLE
Scene 01 (Introduction).txt

### PR DESCRIPTION
**Pull request by MovingGamer**
Added a change log. Checked TS. Changed lit TL.
TS = transcription
TL = translation

### CODE REVIEW

**Comment by MovingGamer** [comment]
I found a YouTube playlist with the first 4 hours or so of the game, so I can help out with some transcription and proofreading now. In case you want to send the playlist to a friend who doesn't have the game, here it is: https://www.youtube.com/playlist?list=PLQA_OfIv4kRXovajaoSsws0q3TWkVr2o3

**Comment by areakryte** [comment]
Thank you so much. I've had a hectic weekend, so progress was 
nonexistent. Could you tell me which sections you want to transcribe so we
don't overlap?

**Comment by areakryte** [comment]
I think this is a full playlist here. Ignore the commentary, he's a Taiwanese let's player. 

https://www.youtube.com/playlist?list=PLhJooBo0H1u_4Nq7N19xIHvc1n7h0OyPW

**Comment by areakryte** [comment]
Alright I got my friend on board to do some editing. Sadly I don't think I can get him to do transcription as it might cut into his Lord of Vermilion time.

**Comment by MovingGamer** [comment]
You're welcome. I'll probably have a few weeks when I don't have time to work on this. Thanks for finding that playlist. The LPer's reading actually helps me because it saves me time looking up the Traditional script words myself.

I use British English by default, but I don't mind using American English for this project. A scene list would be great for keeping track of who's transcribing what. I'll create one to get us started. For now, I'll start transcribing from when Zhao Wei leaves the dorm up to the point he is at the parade with Xiao Yu and Yuan De.

Great to hear Airi has joined us. I think translation/editing is faster than transcription, so that arrangement's fine with me. Will Airi only clean the literal translations, or make them too?

**Comment by areakryte** [comment]
It would be great if he would help since it is technically his first 
language. I might have to bribe him with a trip to a maid cafe or 
something though.

**Comment by MovingGamer** [comment]
Good luck with that! Anyway, I've created a pull request for a scene list. Let me know if you have another idea on how to coordinate the scene transcribing.

**Pull request merged**
